# Advanced features configuration for kg_mad_v3 AVD
# Disable gfxstream backend to prevent crash with VulkanVirtualQueue
GlPipeChecksum = off
GLESDynamicVersion = off
VirtioGpuNativeSync = off
VulkanVirtualQueue = off
VirtioVsockPipe = off
GuestUsesAngle = off
Vulkan = off
