import 'dart:convert';
import 'dart:io';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:file_picker/file_picker.dart';
import 'package:flutter_markdown/flutter_markdown.dart';
import '../../../core/constants/app_theme.dart';
import '../../../data/local/database_helper.dart';
import '../../../services/clipboard_helper.dart';
import '../../../services/tts_flutter_service.dart';
import '../../../services/tts_service.dart';
import '../../../services/auth_service.dart';
import '../../../services/course_context_service.dart';
import '../../../data/local/class_dao.dart';
import '../../../data/local/teaching_dao.dart';
import '../../../services/archive/native_pdf_service.dart';
import '../../../services/video_service.dart';
import '../learning/video_player_page.dart';
import '../materials/courseware_workshop_page.dart';

class LecturePage extends StatefulWidget {
  const LecturePage({super.key});

  @override
  State<LecturePage> createState() => _LecturePageState();
}

class _LecturePageState extends State<LecturePage> {
  String _content = '';
  String _script = '';
  List<String> _videoUrls = [];
  bool _isLoading = true;
  bool _isEditing = false;
  bool _isSpeaking = false;
  bool _showScript = false;
  bool _autoGenerated = false;
  bool _generating = false;
  String _genStatus = '';
  late TextEditingController _editCtrl;
  late TextEditingController _scriptCtrl;

  String _teacherName = '';
  List<Map<String, dynamic>> _classes = [];
  List<Map<String, dynamic>> _syllabus = [];
  List<Map<String, dynamic>> _progress = [];
  int _totalStudents = 0;
  String _courseName = '';

  @override
  void initState() {
    super.initState();
    _editCtrl = TextEditingController();
    _scriptCtrl = TextEditingController();
    _loadContent();
  }

  @override
  void dispose() {
    TtsFlutterService.instance.stop();
    _editCtrl.dispose();
    _scriptCtrl.dispose();
    super.dispose();
  }

  String get _dataDir => 'data/$_courseName';

  Future<void> _loadContent() async {
    _courseName = CourseContextService.defaultCourseName;
    await _gatherContextData();
    try {
      await _loadFromFileSystem();
      if (_content.isNotEmpty) {
        _editCtrl.text = _content;
        if (_teacherName.isNotEmpty && !_autoGenerated) {
          _content = await _buildCompleteLecture();
          _autoGenerated = true;
          _editCtrl.text = _content;
        }
        await _saveToDb(_content, _videoUrls);
        _scanVideoDirs();
        _generateScript();
        if (mounted) setState(() => _isLoading = false);
        return;
      }
    } catch (_) {}

    try {
      final db = await DatabaseHelper.instance.database;
      final rows = await db.query('lecture_notes', where: 'course_id = ?', whereArgs: ['default'], limit: 1);
      if (rows.isNotEmpty && rows.first['content'] != null && (rows.first['content'] as String).isNotEmpty) {
        _content = rows.first['content'] as String;
        _videoUrls = _parseVideoUrls(rows.first['video_urls']);
        _script = rows.first['script'] as String? ?? '';
      } else {
        _content = await rootBundle.loadString('assets/说课/说课.md');
        if (_teacherName.isNotEmpty) _content = await _buildCompleteLecture();
        await _saveToDb(_content, _videoUrls);
        _generateScript();
      }
    } catch (e) {
      try {
        _content = await rootBundle.loadString('assets/说课/说课.md');
        _generateScript();
      } catch (_) {
        _content = '# 说课\n\n内容加载失败。';
      }
    }
    _editCtrl.text = _content;
    _scriptCtrl.text = _script;
    _scanVideoDirs();
    if (mounted) setState(() => _isLoading = false);
  }

  Future<void> _loadFromFileSystem() async {
    final candidates = [
      '$_dataDir/说课/说课.md',
    ];
    for (final relative in candidates) {
      final file = File(relative);
      if (await file.exists()) {
        _content = await file.readAsString();
        _videoUrls = [];
        return;
      }
    }
    throw Exception('说课文件未找到');
  }

  void _scanVideoDirs() {
    _videoUrls = _parseVideoUrls(null);
    final dirs = ['$_dataDir/视频', '$_dataDir/说课'];
    for (final dirPath in dirs) {
      final dir = Directory(dirPath);
      if (!dir.existsSync()) continue;
      for (final f in dir.listSync()) {
        if (f is File) {
          final ext = f.path.split('.').last.toLowerCase();
          if (['mp4', 'avi', 'mkv', 'mov', 'wmv', 'flv'].contains(ext)) {
            if (!_videoUrls.contains(f.path)) {
              _videoUrls.add(f.path);
            }
          }
        }
      }
    }
    _saveVideoUrls();
  }

  Future<void> _gatherContextData() async {
    try {
      final auth = AuthService();
      _teacherName = auth.currentUser?.realName ?? '';
      final teacherId = auth.currentUser?.userId ?? '';
      if (teacherId.isNotEmpty) {
        try {
          final classDao = ClassDao();
          _classes = await classDao.getTeacherClasses(teacherId);
          for (final c in _classes) { _totalStudents += (c['student_count'] as int? ?? 0); }
        } catch (_) {}
      }
      try {
        final teachingDao = TeachingDao();
        _syllabus = await teachingDao.getAllSyllabusItems();
        _progress = await teachingDao.getAllTeachingProgress();
      } catch (_) {}
    } catch (_) {}
  }

  Future<String> _buildCompleteLecture() async {
    final buf = StringBuffer();
    buf.writeln('# 《$_courseName》说课');
    buf.writeln();
    if (_teacherName.isNotEmpty) { buf.writeln('**说课教师**：$_teacherName'); buf.writeln(); }
    if (_classes.isNotEmpty) {
      buf.writeln('## 授课班级'); buf.writeln();
      buf.writeln('| 班级 | 人数 |'); buf.writeln('|------|:---:|');
      for (final c in _classes) {
        buf.writeln('| ${c['name']} | ${c['student_count'] ?? 0} |');
      }
      buf.writeln('| **合计** | **$_totalStudents** |'); buf.writeln();
    }
    if (_syllabus.isNotEmpty) {
      buf.writeln('## 教学大纲'); buf.writeln();
      buf.writeln('| 章 | 主题 | 学时 |'); buf.writeln('|:--:|------|:---:|');
      for (final item in _syllabus) {
        buf.writeln('| ${item['chapter_number']} | ${item['title']} | ${item['hours'] ?? 2} |');
      }
      buf.writeln();
    }
    if (_progress.isNotEmpty) {
      buf.writeln('## 教学进度'); buf.writeln();
      buf.writeln('| 章 | 主题 | 状态 |'); buf.writeln('|:--:|------|:----:|');
      for (final p in _progress) {
        buf.writeln('| ${p['chapter']} | ${p['topic'] ?? ''} | ${p['status'] ?? 'planned'} |');
      }
      buf.writeln();
    }
    buf.writeln('---'); buf.writeln();
    buf.writeln('## 说课正文'); buf.writeln();
    buf.writeln('《$_courseName》（CKGDT）是面向多课程的 Flutter 全平台教学平台。系统围绕"教—学—练—评—管"五个维度构建：知识图谱浏览、章节测验、视频教程、课程资料、实验管理、作品展示、成绩达成、AI 多智能体辅助。支持教师端和学生端差异化导航。');
    return buf.toString();
  }

  void _generateScript() {
    final sb = StringBuffer();
    sb.writeln('各位评委老师好，我是$_teacherName，今天我说课的主题是《$_courseName》。');
    sb.writeln();
    sb.writeln('本课程是面向计算机科学与技术、软件工程、人工智能等专业的专业选修课程，共48学时，其中理论24学时，实践24学时。考核方式为考查，过程考核占百分之五十，期末作品占百分之五十。');
    sb.writeln();
    sb.writeln('课程的核心理念是：以知识图谱为骨架、数字孪生为镜像、AI智能体为辅助，构建教学练评管五位一体的课程教学闭环。学生既是学习者也是数字孪生数据的生产者，教师通过多智能体协同实现个性化教学。');
    sb.writeln();
    sb.writeln('课程理论教学共六章。第一章，课程知识图谱基础，包括概念、表示、构建和查询，培养图谱思维。第二章，课程数据建模与资源治理，学习ER关系、图建模和资源治理策略，培养数据建模能力。第三章，数字孪生教学场景设计，包括镜像、仿真和交互，培养场景设计能力。第四章，智能学习路径与学习分析，包括路径推荐、行为分析和预测，培养分析能力。第五章，实验实践与作品评价，包括实验设计、评价量规和AI批阅，培养评价设计能力。第六章，课程持续改进与平台应用，包括数据分析、反馈闭环和平台运营，培养持续改进能力。');
    sb.writeln();
    sb.writeln('实践教学包括五个实验项目。实验一是图谱构建，对应第一、二章内容。实验二是资源治理。实验三是数字孪生设计。实验四是学习分析实现。实验五是作品评价与改进。实验贯穿整个学期，每个实验4到6学时。');
    sb.writeln();
    if (_classes.isNotEmpty) {
      sb.writeln('本学期授课班级共${_classes.length}个班级，合计 $_totalStudents 名学生。');
      for (final c in _classes) {
        sb.writeln('${c['name']}班，${c['student_count'] ?? 0}人。');
      }
      sb.writeln();
    }
    sb.writeln('平台特色功能包括：一、知识图谱可视化浏览，学生可以直观地看到知识点之间的关联。二、数字孪生教学，每个学生都拥有自己的学习镜像，数据驱动个性化学习。三、多智能体AI辅助，包括智能辅导、测验生成、实验指导、作品批阅等19个专业智能体。四、全流程考核评价，支持平时考核、实验考核、期末作品的三维评价体系。五、学习分析与达成度，学生可以查看自己的学习数据，制定改进计划。');
    sb.writeln();
    sb.writeln('在教学改革方面，本课程持续引入创新。二零二四年引入数字孪生教学，学生参与度提升百分之三十五。知识图谱取代传统目录式教学，知识留存率提升百分之二十八。二零二五年多智能体AI辅助系统上线，答疑响应时间缩短百分之八十。二零二六年实现一键生课平台化，支持任意课程快速部署。');
    sb.writeln();
    sb.writeln('以上就是我的说课内容，请各位评委老师批评指正。谢谢。');
    _script = sb.toString();
    _scriptCtrl.text = _script;
    _saveScript();
  }

  String _stripMarkdown(String md) {
    var text = md;
    text = text.replaceAll(RegExp(r'```[\s\S]*?```'), '');
    text = text.replaceAll(RegExp(r'`[^`]+`'), '');
    text = text.replaceAll(RegExp(r'!\[([^\]]*)\]\([^)]+\)'), '');
    text = text.replaceAll(RegExp(r'\[([^\]]+)\]\([^)]+\)'), r'$1');
    text = text.replaceAll(RegExp(r'[*_]{1,3}'), '');
    text = text.replaceAll(RegExp(r'^#{1,6}\s+', multiLine: true), '');
    text = text.replaceAll(RegExp(r'^[-*_]{3,}\s*$', multiLine: true), '');
    text = text.replaceAll(RegExp(r'\|'), ' ');
    text = text.replaceAll(RegExp(r'^[-:\s|]+$', multiLine: true), '');
    text = text.replaceAll(RegExp(r'^[-*+]\s+', multiLine: true), '');
    text = text.replaceAll(RegExp(r'^\d+\.\s+', multiLine: true), '');
    text = text.replaceAll(RegExp(r'\n{3,}'), '\n\n');
    return text.trim();
  }

  List<String> _parseVideoUrls(dynamic value) {
    final urls = <String>[];
    if (value != null) {
      try { urls.addAll(List<String>.from(jsonDecode(value as String))); } catch (_) {}
    }
    return urls;
  }

  Future<void> _saveToDb(String content, List<String> urls) async {
    try {
      final db = await DatabaseHelper.instance.database;
      final rows = await db.query('lecture_notes', where: 'course_id = ?', whereArgs: ['default'], limit: 1);
      final data = {'content': content, 'video_urls': jsonEncode(urls), 'script': _script, 'updated_at': DateTime.now().toIso8601String()};
      if (rows.isEmpty) {
        await db.insert('lecture_notes', {'course_id': 'default', 'title': '说课', ...data});
      } else {
        await db.update('lecture_notes', data, where: 'course_id = ?', whereArgs: ['default']);
      }
    } catch (_) {}
  }

  Future<void> _saveContent() async {
    _content = _editCtrl.text; _generateScript();
    try {
      final db = await DatabaseHelper.instance.database;
      await db.update('lecture_notes', {'content': _content, 'video_urls': jsonEncode(_videoUrls), 'script': _script, 'updated_at': DateTime.now().toIso8601String()}, where: 'course_id = ?', whereArgs: ['default']);
      if (mounted) { ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('说课内容已保存'))); setState(() => _isEditing = false); }
    } catch (e) { if (mounted) { ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('保存失败: $e'), backgroundColor: Colors.red)); } }
  }

  Future<void> _importFromFile() async {
    try {
      final result = await FilePicker.platform.pickFiles(type: FileType.custom, allowedExtensions: ['md', 'markdown', 'txt']);
      if (result == null || result.files.isEmpty) return;
      final file = File(result.files.single.path!);
      final imported = await file.readAsString();
      _editCtrl.text = imported; _content = imported; _generateScript();
      if (mounted) { setState(() {}); ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('文件已导入'))); }
    } catch (e) { if (mounted) { ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('导入失败: $e'), backgroundColor: Colors.red)); } }
  }

  Future<void> _addVideo() async {
    final result = await FilePicker.platform.pickFiles(type: FileType.custom, allowedExtensions: ['mp4', 'avi', 'mkv', 'mov', 'wmv', 'flv']);
    if (result == null || result.files.isEmpty) return;
    final path = result.files.single.path; if (path == null) return;
    if (!mounted) return; setState(() => _videoUrls.add(path)); _saveVideoUrls();
  }

  void _removeVideo(int index) { setState(() => _videoUrls.removeAt(index)); _saveVideoUrls(); }

  Future<void> _saveVideoUrls() async {
    try {
      final db = await DatabaseHelper.instance.database;
      await db.update('lecture_notes', {'video_urls': jsonEncode(_videoUrls), 'updated_at': DateTime.now().toIso8601String()}, where: 'course_id = ?', whereArgs: ['default']);
    } catch (_) {}
  }

  Future<void> _saveScript() async {
    try {
      final db = await DatabaseHelper.instance.database;
      await db.update('lecture_notes', {'script': _script, 'updated_at': DateTime.now().toIso8601String()}, where: 'course_id = ?', whereArgs: ['default']);
    } catch (_) {}
  }

  Future<void> _speakContent() async {
    final tts = TtsFlutterService.instance;
    if (_isSpeaking) { await tts.stop(); if (mounted) setState(() => _isSpeaking = false); return; }
    final text = _script.isNotEmpty ? _script : _stripMarkdown(_content);
    if (text.isEmpty) return; setState(() => _isSpeaking = true);
    await tts.speak(text); if (mounted) setState(() => _isSpeaking = false);
  }

  void _openVideo(String path) {
    if (!Platform.isWindows && !Platform.isLinux && !Platform.isMacOS) return;
    Navigator.push(context, MaterialPageRoute(builder: (_) => InAppVideoPlayerPage(filePath: path, title: path.split(Platform.pathSeparator).last, chapter: '说课')));
  }

  void _openCoursewareWorkshop() {
    Navigator.push(context, MaterialPageRoute(builder: (_) => const CoursewareWorkshopPage()));
  }

  Future<void> _exportPdf() async {
    try {
      final pdfBytes = await NativePdfService.instance.markdownToPdf(_content);
      final outDir = await _ensureExportDir();
      final path = '$outDir说课_$_courseName.pdf';
      await File(path).writeAsBytes(pdfBytes);
      if (mounted) ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('PDF 已导出: $path'), backgroundColor: Colors.green));
    } catch (e) {
      if (mounted) ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('PDF 导出失败: $e'), backgroundColor: Colors.red));
    }
  }

  Future<String> _ensureExportDir() async {
    final dirs = ['$_dataDir/说课/', '$_dataDir/视频/'];
    for (final d in dirs) {
      final dir = Directory(d);
      if (!dir.existsSync()) await dir.create(recursive: true);
    }
    return dirs[0];
  }

  Future<void> _generateLectureVideo() async {
    setState(() { _generating = true; _genStatus = '正在准备视频生成...'; });

    try {
      final script = _script.isNotEmpty ? _script : _stripMarkdown(_content);
      final paragraphs = script.split('\n').where((l) => l.trim().isNotEmpty).toList();
      final outDir = '$_dataDir说课/';
      Directory(outDir).createSync(recursive: true);

      setState(() => _genStatus = '正在生成语音...');
      final ttsService = TtsService();
      final audioDir = '${outDir}audio/';
      Directory(audioDir).createSync(recursive: true);
      final audios = <String>[];
      final narrations = <Map<String, String>>[];

      for (var i = 0; i < paragraphs.length; i++) {
        narrations.add({'narration': paragraphs[i], 'voice': 'zh-CN-XiaoxiaoNeural', 'rate': '+0%'});
      }

      await ttsService.generateBatchAudio(scripts: narrations, outputDir: audioDir, onProgress: (current, total) {
        setState(() => _genStatus = '正在生成语音... $current/$total');
      });

      for (var i = 0; i < paragraphs.length; i++) {
        final audioPath = '${audioDir}slide_${i.toString().padLeft(3, '0')}.mp3';
        if (await File(audioPath).exists()) audios.add(audioPath);
      }

      setState(() => _genStatus = '正在生成视频...');
      final videoService = VideoService();
      final screenshots = Directory('assets/help/archievement').existsSync()
          ? Directory('assets/help/archievement').listSync().whereType<File>().map((f) => f.path).where((p) => p.endsWith('.png')).take(audios.length).toList()
          : <String>[];

      final slides = <String>[];
      if (screenshots.isNotEmpty) {
        for (var i = 0; i < audios.length; i++) {
          slides.add(screenshots[i % screenshots.length]);
        }
      } else {
        slides.addAll(List.filled(audios.length, ''));
      }

      final videoPath = '$outDir说课演示_$_courseName.mp4';
      final success = await videoService.generateVideo(
        slides: slides,
        audios: audios,
        outputPath: videoPath,
        onProgress: (c, t, m) => setState(() => _genStatus = m),
      );

      if (success && await File(videoPath).exists()) {
        setState(() { _videoUrls.add(videoPath); _generating = false; _genStatus = ''; });
        _saveVideoUrls();
        if (mounted) {
          ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('视频已生成: $videoPath'), backgroundColor: Colors.green));
          _openVideo(videoPath);
        }
      } else {
        setState(() { _generating = false; _genStatus = '视频生成失败'; });
        if (mounted) ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('视频生成失败，请检查 TTS/FFmpeg 是否可用'), backgroundColor: Colors.red));
      }
    } catch (e) {
      setState(() { _generating = false; _genStatus = '生成出错'; });
      if (mounted) ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('生成出错: $e'), backgroundColor: Colors.red));
    }
  }

  @override
  Widget build(BuildContext context) {
    final isPrint = AppGradientTheme.isPrint(context);
    final bgColor = isPrint ? Colors.white : Theme.of(context).scaffoldBackgroundColor;
    final textColor = isPrint ? Colors.black87 : (Theme.of(context).brightness == Brightness.dark ? Colors.white : Colors.black87);
    final accentColor = Theme.of(context).colorScheme.primary;

    return Scaffold(
      backgroundColor: bgColor,
      appBar: AppBar(
        backgroundColor: isPrint ? Colors.white : null,
        title: Text('说课', style: TextStyle(color: isPrint ? Colors.black87 : null)),
        iconTheme: IconThemeData(color: isPrint ? Colors.black87 : null),
        actions: _isEditing
            ? [
                IconButton(icon: const Icon(Icons.undo), tooltip: '取消编辑', onPressed: () { _editCtrl.text = _content; setState(() => _isEditing = false); }),
                IconButton(icon: const Icon(Icons.save_outlined), tooltip: '保存', onPressed: _saveContent),
              ]
            : [
                IconButton(icon: Icon(_isSpeaking ? Icons.stop_circle_outlined : Icons.volume_up_outlined), tooltip: _isSpeaking ? '停止播报' : '语音播报', onPressed: _isLoading ? null : _speakContent),
                if (_videoUrls.isNotEmpty && (Platform.isWindows || Platform.isLinux || Platform.isMacOS))
                  PopupMenuButton<String>(icon: const Icon(Icons.video_library_outlined), tooltip: '视频演示',
                    onSelected: (path) => _openVideo(path),
                    itemBuilder: (_) => _videoUrls.map((path) => PopupMenuItem(value: path, child: Text(path.split(Platform.pathSeparator).last, overflow: TextOverflow.ellipsis))).toList()),
                IconButton(icon: Icon(Icons.record_voice_over_outlined, color: _script.isNotEmpty ? accentColor : null), tooltip: '配音脚本', onPressed: _isLoading ? null : () => setState(() => _showScript = !_showScript)),
                IconButton(icon: const Icon(Icons.picture_as_pdf_outlined), tooltip: '导出 PDF', onPressed: _isLoading ? null : _exportPdf),
                IconButton(icon: const Icon(Icons.smart_display_outlined), tooltip: '课件工坊', onPressed: _isLoading ? null : _openCoursewareWorkshop),
                IconButton(icon: const Icon(Icons.edit_outlined), tooltip: '编辑', onPressed: _isLoading ? null : () => setState(() => _isEditing = true)),
                IconButton(icon: const Icon(Icons.file_upload_outlined), tooltip: '导入 .md', onPressed: _isLoading ? null : () async { await _importFromFile(); if (_isEditing == false) setState(() => _isEditing = true); }),
                IconButton(icon: const Icon(Icons.copy), tooltip: '复制内容', onPressed: _isLoading ? null : () => ClipboardHelper.copyWithToast(context, _content)),
              ],
      ),
      body: _isLoading
          ? const Center(child: CircularProgressIndicator())
          : _generating
              ? _buildGenerationProgress()
              : _isEditing
                  ? _buildEditor(textColor)
                  : _showScript
                      ? _buildScriptView(isPrint)
                      : _buildPreview(isPrint),
    );
  }

  Widget _buildGenerationProgress() {
    return Center(
      child: Column(
        mainAxisSize: MainAxisSize.min,
        children: [
          const CircularProgressIndicator(),
          const SizedBox(height: 24),
          Text(_genStatus, style: const TextStyle(fontSize: 16)),
          const SizedBox(height: 16),
          TextButton(onPressed: () => setState(() => _generating = false), child: const Text('取消')),
        ],
      ),
    );
  }

  Widget _buildScriptView(bool isPrint) {
    final textColor = isPrint ? Colors.black87 : (Theme.of(context).brightness == Brightness.dark ? Colors.white : Colors.black87);
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Container(
          padding: const EdgeInsets.fromLTRB(16, 12, 16, 8),
          child: Row(
            children: [
              const Icon(Icons.record_voice_over, size: 20),
              const SizedBox(width: 8),
              const Text('配音脚本', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16)),
              const Spacer(),
              IconButton(icon: Icon(_isSpeaking ? Icons.stop_circle_outlined : Icons.volume_up), tooltip: _isSpeaking ? '停止' : '试听', onPressed: _speakContent),
              IconButton(icon: const Icon(Icons.edit), tooltip: '编辑脚本', onPressed: () async {
                _scriptCtrl.text = _script;
                final result = await showDialog<String>(context: context, builder: (ctx) => AlertDialog(
                  title: const Text('编辑配音脚本'),
                  content: SizedBox(width: 500, height: 400, child: TextField(controller: _scriptCtrl, maxLines: null, expands: true, textAlignVertical: TextAlignVertical.top, style: const TextStyle(fontFamily: 'monospace', fontSize: 13), decoration: const InputDecoration(border: OutlineInputBorder(), contentPadding: EdgeInsets.all(12)))),
                  actions: [TextButton(onPressed: () => Navigator.pop(ctx), child: const Text('取消')), ElevatedButton(onPressed: () => Navigator.pop(ctx, _scriptCtrl.text), child: const Text('保存'))],
                ));
                if (result != null && mounted) { _script = result; _scriptCtrl.text = _script; _saveScript(); ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('脚本已保存'))); }
              }),
              TextButton.icon(icon: const Icon(Icons.smart_display, size: 18), label: const Text('生成视频'), onPressed: _generateLectureVideo),
            ],
          ),
        ),
        const Divider(height: 1),
        Expanded(child: SingleChildScrollView(padding: const EdgeInsets.all(16), child: SelectableText(_script.isEmpty ? '暂无配音脚本，保存说课内容后将自动生成。' : _script, style: TextStyle(fontSize: 14, height: 1.8, color: textColor)))),
      ],
    );
  }

  Widget _buildEditor(Color textColor) {
    return Column(children: [
      Expanded(child: Padding(padding: const EdgeInsets.all(8), child: TextField(controller: _editCtrl, maxLines: null, expands: true, textAlignVertical: TextAlignVertical.top, style: TextStyle(fontFamily: 'monospace', fontSize: 13, color: textColor), decoration: InputDecoration(border: OutlineInputBorder(borderRadius: BorderRadius.circular(8), borderSide: BorderSide(color: Colors.grey.shade300)), contentPadding: const EdgeInsets.all(12), hintText: '输入 Markdown 内容...')))),
      _buildVideoEditor(),
    ]);
  }

  Widget _buildVideoEditor() {
    return Container(padding: const EdgeInsets.fromLTRB(12, 0, 12, 12), child: Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisSize: MainAxisSize.min, children: [
      Row(children: [const Icon(Icons.video_library_outlined, size: 18), const SizedBox(width: 6), const Text('视频演示', style: TextStyle(fontWeight: FontWeight.w600)), const Spacer(), TextButton.icon(icon: const Icon(Icons.add, size: 18), label: const Text('添加视频'), onPressed: _addVideo)]),
      if (_videoUrls.isEmpty) Padding(padding: const EdgeInsets.symmetric(vertical: 4), child: Text('暂无视频，点击"添加视频"选择文件或放入 data/课程知识图谱与数字孪生/视频/ 目录', style: TextStyle(color: Colors.grey.shade500, fontSize: 13)))
      else ...List.generate(_videoUrls.length, (i) {
        final name = _videoUrls[i].split(Platform.pathSeparator).last;
        return ListTile(dense: true, leading: const Icon(Icons.play_circle_outline, size: 20), title: Text(name, style: const TextStyle(fontSize: 13), overflow: TextOverflow.ellipsis), trailing: IconButton(icon: const Icon(Icons.delete_outline, size: 18), onPressed: () => _removeVideo(i)));
      }),
    ]));
  }

  Widget _buildPreview(bool isPrint) {
    final showVideos = _videoUrls.isNotEmpty && (Platform.isWindows || Platform.isLinux || Platform.isMacOS);
    if (!showVideos) {
      return Markdown(data: _content, selectable: true, styleSheet: _buildStyleSheet(isPrint), onTapLink: (text, href, title) { if (href != null) { Clipboard.setData(ClipboardData(text: href)); ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('已复制链接: $href'))); } });
    }
    return CustomScrollView(slivers: [
      SliverToBoxAdapter(child: Markdown(data: _content, selectable: true, shrinkWrap: true, styleSheet: _buildStyleSheet(isPrint), onTapLink: (text, href, title) { if (href != null) { Clipboard.setData(ClipboardData(text: href)); ScaffoldMessenger.of(context).showSnackBar(SnackBar(content: Text('已复制链接: $href'))); } })),
      SliverToBoxAdapter(child: _buildVideoPreviewSection(isPrint)),
    ]);
  }

  Widget _buildVideoPreviewSection(bool isPrint) {
    return Container(margin: const EdgeInsets.fromLTRB(12, 0, 12, 24), padding: const EdgeInsets.all(12), decoration: BoxDecoration(color: isPrint ? Colors.grey.shade50 : Theme.of(context).cardColor, borderRadius: BorderRadius.circular(8), border: Border.all(color: isPrint ? Colors.grey.shade300 : Colors.grey.shade700.withValues(alpha: 0.3))), child: Column(crossAxisAlignment: CrossAxisAlignment.start, mainAxisSize: MainAxisSize.min, children: [
      Row(children: [Icon(Icons.video_library, size: 20, color: isPrint ? Colors.black54 : null), const SizedBox(width: 6), Text('视频演示', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 15, color: isPrint ? Colors.black87 : null)), const Spacer(), TextButton.icon(icon: const Icon(Icons.smart_display, size: 18), label: const Text('生成说课视频'), onPressed: _generateLectureVideo)]),
      const SizedBox(height: 8),
      if (_videoUrls.isEmpty) Padding(padding: const EdgeInsets.symmetric(vertical: 8), child: Text('暂无视频，请先"生成说课视频"或放入视频文件到 data/ 目录', style: TextStyle(color: Colors.grey.shade500, fontSize: 13)))
      else ...List.generate(_videoUrls.length, (i) {
        final name = _videoUrls[i].split(Platform.pathSeparator).last;
        return Card(margin: const EdgeInsets.only(bottom: 6), child: ListTile(dense: true, leading: const Icon(Icons.play_circle_fill, color: Colors.blue), title: Text(name, style: const TextStyle(fontSize: 13), overflow: TextOverflow.ellipsis), trailing: const Icon(Icons.chevron_right, size: 18), onTap: () => _openVideo(_videoUrls[i])));
      }),
    ]));
  }

  MarkdownStyleSheet _buildStyleSheet(bool isPrint) {
    const accentColor = Color(0xFF1677FF);
    final textColor = isPrint ? Colors.black87 : (Theme.of(context).brightness == Brightness.dark ? Colors.white : Colors.black87);
    const baseFontSize = 14.0;
    final isDark = !isPrint && Theme.of(context).brightness == Brightness.dark;
    return MarkdownStyleSheet(
      p: TextStyle(fontSize: baseFontSize, height: 1.7, color: textColor),
      h1: TextStyle(fontSize: baseFontSize + 8, fontWeight: FontWeight.bold, height: 1.5, color: textColor),
      h2: TextStyle(fontSize: baseFontSize + 4, fontWeight: FontWeight.bold, height: 1.5, color: textColor),
      h3: TextStyle(fontSize: baseFontSize + 2, fontWeight: FontWeight.w600, height: 1.4, color: textColor),
      h4: TextStyle(fontSize: baseFontSize + 1, fontWeight: FontWeight.w600, height: 1.4, color: textColor),
      strong: TextStyle(fontWeight: FontWeight.bold, color: textColor),
      em: TextStyle(fontStyle: FontStyle.italic, color: textColor),
      code: TextStyle(fontFamily: 'monospace', fontSize: baseFontSize - 1, color: isDark ? Colors.amber[300] : Colors.deepPurple[700], backgroundColor: isDark ? Colors.white.withValues(alpha: 0.08) : Colors.deepPurple.withValues(alpha: 0.06)),
      codeblockPadding: const EdgeInsets.all(14),
      codeblockDecoration: BoxDecoration(color: isDark ? Colors.white.withValues(alpha: 0.06) : Colors.grey.withValues(alpha: 0.08), borderRadius: BorderRadius.circular(8), border: Border.all(color: isDark ? Colors.white.withValues(alpha: 0.1) : Colors.grey.withValues(alpha: 0.2))),
      blockquoteDecoration: BoxDecoration(color: isDark ? accentColor.withValues(alpha: 0.08) : accentColor.withValues(alpha: 0.04), border: const Border(left: BorderSide(color: accentColor, width: 4))),
      blockquotePadding: const EdgeInsets.fromLTRB(12, 8, 12, 8),
      listBullet: const TextStyle(fontSize: baseFontSize, color: accentColor),
      tableHead: TextStyle(fontSize: baseFontSize - 1, fontWeight: FontWeight.bold, color: textColor),
      tableBody: TextStyle(fontSize: baseFontSize - 1, color: textColor),
      tableBorder: TableBorder.all(color: isDark ? Colors.white.withValues(alpha: 0.15) : Colors.grey.withValues(alpha: 0.3)),
      tableCellsPadding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
      horizontalRuleDecoration: BoxDecoration(border: Border(top: BorderSide(color: isDark ? Colors.white.withValues(alpha: 0.15) : Colors.grey.withValues(alpha: 0.3)))),
      blockSpacing: 10,
    );
  }
}
