import 'dart:convert';
import 'dart:io';
import 'package:flutter/material.dart';
import 'package:flutter/services.dart';
import 'package:file_picker/file_picker.dart';
import 'package:flutter_markdown/flutter_markdown.dart';
import '../../../core/constants/app_theme.dart';
import '../../../data/local/database_helper.dart';
import '../../../services/clipboard_helper.dart';
import '../../../services/tts_flutter_service.dart';
import '../../../services/auth_service.dart';
import '../../../data/local/class_dao.dart';
import '../../../data/local/teaching_dao.dart';
import '../learning/video_player_page.dart';
import '../materials/courseware_workshop_page.dart';

class LecturePage extends StatefulWidget {
  const LecturePage({super.key});

  @override
  State<LecturePage> createState() => _LecturePageState();
}

class _LecturePageState extends State<LecturePage> {
  String _content = '';
  String _script = '';
  List<String> _videoUrls = [];
  bool _isLoading = true;
  bool _isEditing = false;
  bool _isSpeaking = false;
  bool _showScript = false;
  bool _autoGenerated = false;
  late TextEditingController _editCtrl;
  late TextEditingController _scriptCtrl;

  String _teacherName = '';
  List<Map<String, dynamic>> _classes = [];
  List<Map<String, dynamic>> _syllabus = [];
  List<Map<String, dynamic>> _progress = [];
  int _totalStudents = 0;

  @override
  void initState() {
    super.initState();
    _editCtrl = TextEditingController();
    _scriptCtrl = TextEditingController();
    _loadContent();
  }

  @override
  void dispose() {
    TtsFlutterService.instance.stop();
    _editCtrl.dispose();
    _scriptCtrl.dispose();
    super.dispose();
  }

  Future<void> _loadContent() async {
    try {
      await _loadFromFileSystem();
      if (_content.isNotEmpty) {
        _editCtrl.text = _content;
        await _gatherContextData();
        if (_teacherName.isNotEmpty && !_autoGenerated) {
          _content = await _buildCompleteLecture();
          _autoGenerated = true;
          _editCtrl.text = _content;
        }
        await _saveToDb(_content, _videoUrls);
        _generateScript();
        if (mounted) setState(() => _isLoading = false);
        return;
      }
    } catch (_) {}

    try {
      final db = await DatabaseHelper.instance.database;
      final rows = await db.query(
        'lecture_notes',
        where: 'course_id = ?',
        whereArgs: ['default'],
        limit: 1,
      );
      if (rows.isNotEmpty && rows.first['content'] != null && (rows.first['content'] as String).isNotEmpty) {
        _content = rows.first['content'] as String;
        _videoUrls = _parseVideoUrls(rows.first['video_urls']);
        _script = rows.first['script'] as String? ?? '';
      } else {
        _content = await rootBundle.loadString('assets/说课/说课.md');
        _videoUrls = [];
        await _gatherContextData();
        if (_teacherName.isNotEmpty) {
          _content = await _buildCompleteLecture();
        }
        await _saveToDb(_content, _videoUrls);
        _generateScript();
      }
    } catch (e) {
      try {
        _content = await rootBundle.loadString('assets/说课/说课.md');
        _videoUrls = [];
        _generateScript();
      } catch (_) {
        _content = '# 说课\n\n内容加载失败。';
      }
    }
    _editCtrl.text = _content;
    _scriptCtrl.text = _script;
    if (mounted) setState(() => _isLoading = false);
  }

  Future<void> _loadFromFileSystem() async {
    final candidates = [
      'data/课程知识图谱与数字孪生/说课/说课.md',
    ];
    for (final relative in candidates) {
      final file = File(relative);
      if (await file.exists()) {
        _content = await file.readAsString();
        _videoUrls = [];
        return;
      }
    }
    throw Exception('说课文件未找到');
  }

  Future<void> _gatherContextData() async {
    try {
      final auth = AuthService();
      _teacherName = auth.currentUser?.realName ?? '';
      final teacherId = auth.currentUser?.userId ?? '';
      if (teacherId.isNotEmpty) {
        try {
          final classDao = ClassDao();
          _classes = await classDao.getTeacherClasses(teacherId);
          _totalStudents = 0;
          for (final c in _classes) {
            _totalStudents += (c['student_count'] as int? ?? 0);
          }
        } catch (_) {}
      }
      try {
        final teachingDao = TeachingDao();
        _syllabus = await teachingDao.getAllSyllabusItems();
        _progress = await teachingDao.getAllTeachingProgress();
      } catch (_) {}
    } catch (_) {}
  }

  Future<String> _buildCompleteLecture() async {
    final buf = StringBuffer();
    buf.writeln('# 《课程知识图谱与数字孪生平台》说课');
    buf.writeln();

    if (_teacherName.isNotEmpty) {
      buf.writeln('**说课教师**：$_teacherName');
      buf.writeln();
    }

    if (_classes.isNotEmpty) {
      buf.writeln('## 授课班级');
      buf.writeln();
      buf.writeln('| 班级 | 人数 |');
      buf.writeln('|------|:---:|');
      for (final c in _classes) {
        final name = c['name']?.toString() ?? '';
        final count = c['student_count'] as int? ?? 0;
        buf.writeln('| $name | $count |');
      }
      buf.writeln('| **合计** | **$_totalStudents** |');
      buf.writeln();
    }

    if (_syllabus.isNotEmpty) {
      buf.writeln('## 教学大纲');
      buf.writeln();
      buf.writeln('| 章 | 主题 | 学时 |');
      buf.writeln('|:--:|------|:---:|');
      for (final item in _syllabus) {
        final ch = item['chapter_number'] ?? '';
        final title = item['title']?.toString() ?? '';
        final hours = item['hours'] ?? 2;
        buf.writeln('| $ch | $title | $hours |');
      }
      buf.writeln();
    }

    if (_progress.isNotEmpty) {
      buf.writeln('## 教学进度');
      buf.writeln();
      buf.writeln('| 章 | 主题 | 状态 |');
      buf.writeln('|:--:|------|:----:|');
      for (final p in _progress) {
        final ch = p['chapter'] ?? '';
        final topic = p['topic']?.toString() ?? '';
        final status = p['status']?.toString() ?? 'planned';
        buf.writeln('| $ch | $topic | $status |');
      }
      buf.writeln();
    }

    buf.writeln('---');
    buf.writeln();
    buf.writeln('## 说课正文');
    buf.writeln();
    buf.writeln('《课程知识图谱与数字孪生平台》是面向多课程的 Flutter 全平台教学平台。系统围绕"教—学—练—评—管"五个维度构建：知识图谱浏览、章节测验、视频教程、课程资料、实验管理、作品展示、成绩达成、AI 多智能体辅助。');

    return buf.toString();
  }

  void _generateScript() {
    _script = _stripMarkdown(_content);
    _scriptCtrl.text = _script;
    _saveScript();
  }

  String _stripMarkdown(String md) {
    var text = md;
    text = text.replaceAll(RegExp(r'```[\s\S]*?```'), '');
    text = text.replaceAll(RegExp(r'`[^`]+`'), '');
    text = text.replaceAll(RegExp(r'!\[([^\]]*)\]\([^)]+\)'), '');
    text = text.replaceAll(RegExp(r'\[([^\]]+)\]\([^)]+\)'), r'$1');
    text = text.replaceAll(RegExp(r'[*_]{1,3}'), '');
    text = text.replaceAll(RegExp(r'^#{1,6}\s+', multiLine: true), '');
    text = text.replaceAll(RegExp(r'^[-*_]{3,}\s*$', multiLine: true), '');
    text = text.replaceAll(RegExp(r'\|'), ' ');
    text = text.replaceAll(RegExp(r'^[-:\s|]+$', multiLine: true), '');
    text = text.replaceAll(RegExp(r'^[-*+]\s+', multiLine: true), '');
    text = text.replaceAll(RegExp(r'^\d+\.\s+', multiLine: true), '');
    text = text.replaceAll(RegExp(r'\n{3,}'), '\n\n');
    text = text.trim();
    return text;
  }

  Future<void> _saveScript() async {
    try {
      final db = await DatabaseHelper.instance.database;
      await db.update(
        'lecture_notes',
        {'script': _script, 'updated_at': DateTime.now().toIso8601String()},
        where: 'course_id = ?',
        whereArgs: ['default'],
      );
    } catch (_) {}
  }

  List<String> _parseVideoUrls(dynamic value) {
    if (value == null) return [];
    try {
      final list = jsonDecode(value as String);
      return List<String>.from(list);
    } catch (_) {
      return [];
    }
  }

  Future<void> _saveToDb(String content, List<String> urls) async {
    try {
      final db = await DatabaseHelper.instance.database;
      final rows = await db.query('lecture_notes', where: 'course_id = ?', whereArgs: ['default'], limit: 1);
      if (rows.isEmpty) {
        await db.insert('lecture_notes', {
          'course_id': 'default',
          'title': '说课',
          'content': content,
          'video_urls': jsonEncode(urls),
          'script': _script,
          'updated_at': DateTime.now().toIso8601String(),
        });
      } else {
        await db.update(
          'lecture_notes',
          {'content': content, 'video_urls': jsonEncode(urls), 'script': _script, 'updated_at': DateTime.now().toIso8601String()},
          where: 'course_id = ?',
          whereArgs: ['default'],
        );
      }
    } catch (_) {}
  }

  Future<void> _saveContent() async {
    _content = _editCtrl.text;
    _generateScript();
    try {
      final db = await DatabaseHelper.instance.database;
      await db.update(
        'lecture_notes',
        {'content': _content, 'video_urls': jsonEncode(_videoUrls), 'script': _script, 'updated_at': DateTime.now().toIso8601String()},
        where: 'course_id = ?',
        whereArgs: ['default'],
      );
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('说课内容已保存')),
        );
        setState(() => _isEditing = false);
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('保存失败: $e'), backgroundColor: Colors.red),
        );
      }
    }
  }

  Future<void> _importFromFile() async {
    try {
      final result = await FilePicker.platform.pickFiles(
        type: FileType.custom,
        allowedExtensions: ['md', 'markdown', 'txt'],
      );
      if (result == null || result.files.isEmpty) return;
      final file = File(result.files.single.path!);
      final imported = await file.readAsString();
      _editCtrl.text = imported;
      _content = imported;
      _generateScript();
      if (mounted) {
        setState(() {});
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(content: Text('文件已导入')),
        );
      }
    } catch (e) {
      if (mounted) {
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(content: Text('导入失败: $e'), backgroundColor: Colors.red),
        );
      }
    }
  }

  Future<void> _addVideo() async {
    final result = await FilePicker.platform.pickFiles(
      type: FileType.custom,
      allowedExtensions: ['mp4', 'avi', 'mkv', 'mov', 'wmv', 'flv'],
    );
    if (result == null || result.files.isEmpty) return;
    final path = result.files.single.path;
    if (path == null) return;
    if (!mounted) return;
    setState(() => _videoUrls.add(path));
    _saveVideoUrls();
  }

  void _removeVideo(int index) {
    setState(() => _videoUrls.removeAt(index));
    _saveVideoUrls();
  }

  Future<void> _saveVideoUrls() async {
    try {
      final db = await DatabaseHelper.instance.database;
      await db.update(
        'lecture_notes',
        {'video_urls': jsonEncode(_videoUrls), 'updated_at': DateTime.now().toIso8601String()},
        where: 'course_id = ?',
        whereArgs: ['default'],
      );
    } catch (_) {}
  }

  Future<void> _speakContent() async {
    final tts = TtsFlutterService.instance;
    if (_isSpeaking) {
      await tts.stop();
      if (mounted) setState(() => _isSpeaking = false);
      return;
    }
    final text = _script.isNotEmpty ? _script : _stripMarkdown(_content);
    if (text.isEmpty) return;
    setState(() => _isSpeaking = true);
    await tts.speak(text);
    if (mounted) setState(() => _isSpeaking = false);
  }

  void _openVideo(String path) {
    if (!Platform.isWindows && !Platform.isLinux && !Platform.isMacOS) return;
    Navigator.push(context, MaterialPageRoute(
      builder: (_) => InAppVideoPlayerPage(
        filePath: path,
        title: path.split(Platform.pathSeparator).last,
        chapter: '说课',
      ),
    ));
  }

  void _openCoursewareWorkshop() {
    Navigator.push(context, MaterialPageRoute(
      builder: (_) => const CoursewareWorkshopPage(),
    ));
  }

  @override
  Widget build(BuildContext context) {
    final isPrint = AppGradientTheme.isPrint(context);
    final bgColor = isPrint ? Colors.white : Theme.of(context).scaffoldBackgroundColor;
    final textColor = isPrint ? Colors.black87 : (Theme.of(context).brightness == Brightness.dark ? Colors.white : Colors.black87);
    final accentColor = Theme.of(context).colorScheme.primary;

    return Scaffold(
      backgroundColor: bgColor,
      appBar: AppBar(
        backgroundColor: isPrint ? Colors.white : null,
        title: Text('说课', style: TextStyle(color: isPrint ? Colors.black87 : null)),
        iconTheme: IconThemeData(color: isPrint ? Colors.black87 : null),
        actions: [
          if (!_isEditing) ...[
            IconButton(
              icon: Icon(_isSpeaking ? Icons.stop_circle_outlined : Icons.volume_up_outlined),
              tooltip: _isSpeaking ? '停止播报' : '语音播报',
              onPressed: _isLoading ? null : _speakContent,
            ),
            if (_videoUrls.isNotEmpty && (Platform.isWindows || Platform.isLinux || Platform.isMacOS))
              PopupMenuButton<String>(
                icon: const Icon(Icons.video_library_outlined),
                tooltip: '视频演示',
                onSelected: (path) => _openVideo(path),
                itemBuilder: (_) => _videoUrls.map((path) {
                  final name = path.split(Platform.pathSeparator).last;
                  return PopupMenuItem(value: path, child: Text(name, overflow: TextOverflow.ellipsis));
                }).toList(),
              ),
            IconButton(
              icon: Icon(Icons.record_voice_over_outlined, color: _script.isNotEmpty ? accentColor : null),
              tooltip: '配音脚本',
              onPressed: _isLoading ? null : () => setState(() => _showScript = !_showScript),
            ),
            IconButton(
              icon: const Icon(Icons.smart_display_outlined),
              tooltip: '课件工坊',
              onPressed: _isLoading ? null : _openCoursewareWorkshop,
            ),
            IconButton(
              icon: const Icon(Icons.edit_outlined),
              tooltip: '编辑',
              onPressed: _isLoading ? null : () => setState(() => _isEditing = true),
            ),
            IconButton(
              icon: const Icon(Icons.file_upload_outlined),
              tooltip: '导入 .md',
              onPressed: _isLoading ? null : () async {
                await _importFromFile();
                if (_isEditing == false) setState(() => _isEditing = true);
              },
            ),
            IconButton(
              icon: const Icon(Icons.copy),
              tooltip: '复制内容',
              onPressed: _isLoading ? null : () => ClipboardHelper.copyWithToast(context, _content),
            ),
          ],
          if (_isEditing) ...[
            IconButton(
              icon: const Icon(Icons.undo),
              tooltip: '取消编辑',
              onPressed: () {
                _editCtrl.text = _content;
                setState(() => _isEditing = false);
              },
            ),
            IconButton(
              icon: const Icon(Icons.save_outlined),
              tooltip: '保存',
              onPressed: _saveContent,
            ),
          ],
        ],
      ),
      body: _isLoading
          ? const Center(child: CircularProgressIndicator())
          : _isEditing
              ? _buildEditor(textColor)
              : _showScript
                  ? _buildScriptView(isPrint)
                  : _buildPreview(isPrint),
    );
  }

  Widget _buildScriptView(bool isPrint) {
    final textColor = isPrint ? Colors.black87 : (Theme.of(context).brightness == Brightness.dark ? Colors.white : Colors.black87);
    return Column(
      crossAxisAlignment: CrossAxisAlignment.start,
      children: [
        Container(
          padding: const EdgeInsets.fromLTRB(16, 12, 16, 8),
          child: Row(
            children: [
              const Icon(Icons.record_voice_over, size: 20),
              const SizedBox(width: 8),
              const Text('配音脚本', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 16)),
              const Spacer(),
              IconButton(
                icon: Icon(_isSpeaking ? Icons.stop_circle_outlined : Icons.volume_up),
                tooltip: _isSpeaking ? '停止' : '试听',
                onPressed: _speakContent,
              ),
              IconButton(
                icon: const Icon(Icons.edit),
                tooltip: '编辑脚本',
                onPressed: () async {
                  _scriptCtrl.text = _script;
                  final result = await showDialog<String>(
                    context: context,
                    builder: (ctx) => AlertDialog(
                      title: const Text('编辑配音脚本'),
                      content: SizedBox(
                        width: 500,
                        height: 400,
                        child: TextField(
                          controller: _scriptCtrl,
                          maxLines: null,
                          expands: true,
                          textAlignVertical: TextAlignVertical.top,
                          style: const TextStyle(fontFamily: 'monospace', fontSize: 13),
                          decoration: const InputDecoration(
                            border: OutlineInputBorder(),
                            contentPadding: EdgeInsets.all(12),
                          ),
                        ),
                      ),
                      actions: [
                        TextButton(onPressed: () => Navigator.pop(ctx), child: const Text('取消')),
                        ElevatedButton(onPressed: () => Navigator.pop(ctx, _scriptCtrl.text), child: const Text('保存')),
                      ],
                    ),
                  );
                  if (result != null && mounted) {
                    _script = result;
                    _scriptCtrl.text = _script;
                    _saveScript();
                    ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('脚本已保存')));
                  }
                },
              ),
            ],
          ),
        ),
        const Divider(height: 1),
        Expanded(
          child: SingleChildScrollView(
            padding: const EdgeInsets.all(16),
            child: SelectableText(
              _script.isEmpty ? '暂无配音脚本，保存说课内容后将自动生成。' : _script,
              style: TextStyle(fontSize: 14, height: 1.8, color: textColor),
            ),
          ),
        ),
      ],
    );
  }

  Widget _buildEditor(Color textColor) {
    return Column(
      children: [
        Expanded(
          child: Padding(
            padding: const EdgeInsets.all(8),
            child: TextField(
              controller: _editCtrl,
              maxLines: null,
              expands: true,
              textAlignVertical: TextAlignVertical.top,
              style: TextStyle(
                fontFamily: 'monospace',
                fontSize: 13,
                color: textColor,
              ),
              decoration: InputDecoration(
                border: OutlineInputBorder(
                  borderRadius: BorderRadius.circular(8),
                  borderSide: BorderSide(color: Colors.grey.shade300),
                ),
                contentPadding: const EdgeInsets.all(12),
                hintText: '输入 Markdown 内容...',
              ),
            ),
          ),
        ),
        _buildVideoEditor(),
      ],
    );
  }

  Widget _buildVideoEditor() {
    return Container(
      padding: const EdgeInsets.fromLTRB(12, 0, 12, 12),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        mainAxisSize: MainAxisSize.min,
        children: [
          Row(
            children: [
              const Icon(Icons.video_library_outlined, size: 18),
              const SizedBox(width: 6),
              const Text('视频演示', style: TextStyle(fontWeight: FontWeight.w600)),
              const Spacer(),
              TextButton.icon(
                icon: const Icon(Icons.add, size: 18),
                label: const Text('添加视频'),
                onPressed: _addVideo,
              ),
            ],
          ),
          if (_videoUrls.isEmpty)
            Padding(
              padding: const EdgeInsets.symmetric(vertical: 4),
              child: Text('暂无视频，点击"添加视频"选择文件', style: TextStyle(color: Colors.grey.shade500, fontSize: 13)),
            )
          else
            ...List.generate(_videoUrls.length, (i) {
              final name = _videoUrls[i].split(Platform.pathSeparator).last;
              return ListTile(
                dense: true,
                leading: const Icon(Icons.play_circle_outline, size: 20),
                title: Text(name, style: const TextStyle(fontSize: 13), overflow: TextOverflow.ellipsis),
                trailing: IconButton(
                  icon: const Icon(Icons.delete_outline, size: 18),
                  onPressed: () => _removeVideo(i),
                ),
              );
            }),
        ],
      ),
    );
  }

  Widget _buildPreview(bool isPrint) {
    final showVideos = _videoUrls.isNotEmpty && (Platform.isWindows || Platform.isLinux || Platform.isMacOS);
    if (!showVideos) {
      return Markdown(
        data: _content,
        selectable: true,
        styleSheet: _buildStyleSheet(isPrint),
        onTapLink: (text, href, title) {
          if (href != null) {
            Clipboard.setData(ClipboardData(text: href));
            ScaffoldMessenger.of(context).showSnackBar(
              SnackBar(content: Text('已复制链接: $href')),
            );
          }
        },
      );
    }
    return CustomScrollView(
      slivers: [
        SliverToBoxAdapter(
          child: Markdown(
            data: _content,
            selectable: true,
            shrinkWrap: true,
            styleSheet: _buildStyleSheet(isPrint),
            onTapLink: (text, href, title) {
              if (href != null) {
                Clipboard.setData(ClipboardData(text: href));
                ScaffoldMessenger.of(context).showSnackBar(
                  SnackBar(content: Text('已复制链接: $href')),
                );
              }
            },
          ),
        ),
        SliverToBoxAdapter(child: _buildVideoPreviewSection(isPrint)),
      ],
    );
  }

  Widget _buildVideoPreviewSection(bool isPrint) {
    return Container(
      margin: const EdgeInsets.fromLTRB(12, 0, 12, 24),
      padding: const EdgeInsets.all(12),
      decoration: BoxDecoration(
        color: isPrint ? Colors.grey.shade50 : Theme.of(context).cardColor,
        borderRadius: BorderRadius.circular(8),
        border: Border.all(color: isPrint ? Colors.grey.shade300 : Colors.grey.shade700.withValues(alpha: 0.3)),
      ),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        mainAxisSize: MainAxisSize.min,
        children: [
          Row(
            children: [
              Icon(Icons.video_library, size: 20, color: isPrint ? Colors.black54 : null),
              const SizedBox(width: 6),
              Text('视频演示', style: TextStyle(fontWeight: FontWeight.bold, fontSize: 15, color: isPrint ? Colors.black87 : null)),
            ],
          ),
          const SizedBox(height: 8),
          if (_videoUrls.isEmpty)
            Padding(
              padding: const EdgeInsets.symmetric(vertical: 8),
              child: Text('暂无视频', style: TextStyle(color: Colors.grey.shade500, fontSize: 13)),
            )
          else
            ...List.generate(_videoUrls.length, (i) {
              final name = _videoUrls[i].split(Platform.pathSeparator).last;
              return Card(
                margin: const EdgeInsets.only(bottom: 6),
                child: ListTile(
                  dense: true,
                  leading: const Icon(Icons.play_circle_fill, color: Colors.blue),
                  title: Text(name, style: const TextStyle(fontSize: 13), overflow: TextOverflow.ellipsis),
                  trailing: const Icon(Icons.chevron_right, size: 18),
                  onTap: () => _openVideo(_videoUrls[i]),
                ),
              );
            }),
        ],
      ),
    );
  }

  MarkdownStyleSheet _buildStyleSheet(bool isPrint) {
    const accentColor = Color(0xFF1677FF);
    final textColor = isPrint ? Colors.black87 : (Theme.of(context).brightness == Brightness.dark ? Colors.white : Colors.black87);
    const baseFontSize = 14.0;
    final isDark = !isPrint && Theme.of(context).brightness == Brightness.dark;

    return MarkdownStyleSheet(
      p: TextStyle(fontSize: baseFontSize, height: 1.7, color: textColor),
      h1: TextStyle(fontSize: baseFontSize + 8, fontWeight: FontWeight.bold, height: 1.5, color: textColor),
      h2: TextStyle(fontSize: baseFontSize + 4, fontWeight: FontWeight.bold, height: 1.5, color: textColor),
      h3: TextStyle(fontSize: baseFontSize + 2, fontWeight: FontWeight.w600, height: 1.4, color: textColor),
      h4: TextStyle(fontSize: baseFontSize + 1, fontWeight: FontWeight.w600, height: 1.4, color: textColor),
      strong: TextStyle(fontWeight: FontWeight.bold, color: textColor),
      em: TextStyle(fontStyle: FontStyle.italic, color: textColor),
      code: TextStyle(fontFamily: 'monospace', fontSize: baseFontSize - 1, color: isDark ? Colors.amber[300] : Colors.deepPurple[700], backgroundColor: isDark ? Colors.white.withValues(alpha: 0.08) : Colors.deepPurple.withValues(alpha: 0.06)),
      codeblockPadding: const EdgeInsets.all(14),
      codeblockDecoration: BoxDecoration(color: isDark ? Colors.white.withValues(alpha: 0.06) : Colors.grey.withValues(alpha: 0.08), borderRadius: BorderRadius.circular(8), border: Border.all(color: isDark ? Colors.white.withValues(alpha: 0.1) : Colors.grey.withValues(alpha: 0.2))),
      blockquoteDecoration: BoxDecoration(color: isDark ? accentColor.withValues(alpha: 0.08) : accentColor.withValues(alpha: 0.04), border: const Border(left: BorderSide(color: accentColor, width: 4))),
      blockquotePadding: const EdgeInsets.fromLTRB(12, 8, 12, 8),
      listBullet: const TextStyle(fontSize: baseFontSize, color: accentColor),
      tableHead: TextStyle(fontSize: baseFontSize - 1, fontWeight: FontWeight.bold, color: textColor),
      tableBody: TextStyle(fontSize: baseFontSize - 1, color: textColor),
      tableBorder: TableBorder.all(color: isDark ? Colors.white.withValues(alpha: 0.15) : Colors.grey.withValues(alpha: 0.3)),
      tableCellsPadding: const EdgeInsets.symmetric(horizontal: 8, vertical: 4),
      horizontalRuleDecoration: BoxDecoration(border: Border(top: BorderSide(color: isDark ? Colors.white.withValues(alpha: 0.15) : Colors.grey.withValues(alpha: 0.3)))),
      blockSpacing: 10,
    );
  }
}
