// Auto-generated by scripts/version_bump.dart. DO NOT EDIT manually.
class Version {
  static const int major = 1;
  static const int minor = 16;
  static const int patch = 2;
  static const int build = 2;

  /// Display version: "1.16.2.2"
  static const String display = '1.16.2.2';

  /// Flutter pubspec version: "1.16.2+2"
  static const String pubspec = '1.16.2+2';

  /// 3-part version for platform files: "1.16.2"
  static const String platform = '1.16.2';
}
