/// 版本自动管理脚本 — 单一来源升级。
///
/// 用法:
/// ```bash
/// dart run scripts/version_bump.dart
/// ```
///
/// 功能:
/// 1. 从 `lib/core/version.dart` 读取当前版本 (major.minor.patch.build)
/// 2. 用 `git diff` 检测变更类型 → minor++ / patch++ / build++
/// 3. 写入新 version.dart，同步 10 个平台文件，更新 pubspec 构建号
library;

import 'dart:io';

import 'package:path/path.dart' as p;
import 'package:knowledge_graph_app/services/version_bump_service.dart';

Future<void> main(List<String> args) async {
  final root = _resolveProjectRoot();
  final script = VersionBumpScript(root);
  await script.run();
}

/// 从 cwd 或备用路径解析项目根。
String _resolveProjectRoot() {
  final cwd = Directory.current.path;
  if (File(p.join(cwd, 'pubspec.yaml')).existsSync()) return cwd;
  final alt = r'D:\FlutterProjects\knowledge_graph_app';
  if (File(p.join(alt, 'pubspec.yaml')).existsSync()) return alt;
  throw StateError('找不到项目根目录（pubspec.yaml 不存在）');
}

// ---------------------------------------------------------------------------

class VersionBumpScript {
  final String root;
  late final File versionFile;
  late final File buildInfoFile;

  VersionBumpScript(this.root) {
    versionFile = File(p.join(root, 'lib', 'core', 'version.dart'));
    buildInfoFile = File(p.join(root, 'lib', 'core', 'build_info.dart'));
  }

  // ── 主流程 ──────────────────────────────────────────────────────────

  Future<void> run() async {
    // 1. 读取当前版本
    final (major, minor, patch, build) = await _readVersion();
    final oldDisplay = '$major.$minor.$patch.$build';
    print('当前版本: $oldDisplay');

    // 2. 检测变更类型
    final (bumpMinor, bumpPatch) = _detectBump();
    final newMajor = major;
    final newMinor = bumpMinor ? minor + 1 : minor;
    final newPatch = bumpPatch
        ? patch + 1
        : (bumpMinor ? 0 : patch);
    final newBuild = build + 1;

    final bumpLabel = bumpMinor
        ? 'minor++ (新页面/新功能)'
        : (bumpPatch ? 'patch++ (代码变更)' : 'build++ (配置/文档变更)');
    print('变更类型: $bumpLabel');
    print('新版本  : $newMajor.$newMinor.$newPatch.$newBuild');

    // 3. 写入 version.dart
    await _writeVersion(newMajor, newMinor, newPatch, newBuild);
    print('  ✓ lib/core/version.dart');

    // 4. 确保 build_info.dart 引用 Version.display
    await _ensureBuildInfoUsesVersion();

    // 5. 同步 10 个平台文件（build_info / pubspec / strings.xml / CMakeLists
    //    / main.cpp / Runner.rc / web index.html + manifest.json
    //    / ohos app.json5 / i18n）
    final threePart = '$newMajor.$newMinor.$newPatch';
    print('\n── 同步平台文件 ──');
    final logs = await VersionBumpService.applyVersion(threePart);
    for (final log in logs) {
      print(log);
    }

    // 6. 覆盖 pubspec 正确的构建号（applyVersion 会写成 +0，我们覆盖成 +build）
    await _updatePubspecBuild(newMajor, newMinor, newPatch, newBuild);
    final pubspecVer = '$newMajor.$newMinor.$newPatch+$newBuild';
    print('  ✓ pubspec.yaml → $pubspecVer');

    // 7. 汇总
    final newDisplay = '$newMajor.$newMinor.$newPatch.$newBuild';
    print('\n✅ 版本升级完成: $oldDisplay → $newDisplay');
    print('   Display: $newDisplay');
    print('   Pubspec: $pubspecVer');
  }

  // ── 版本读写 ────────────────────────────────────────────────────────

  /// 解析 version.dart 中的 4 个整数常量。
  Future<(int, int, int, int)> _readVersion() async {
    final src = await versionFile.readAsString();
    int parse(String name) {
      final re = RegExp('static const int $name\\s*=\\s*(\\d+);');
      final m = re.firstMatch(src);
      if (m == null) throw StateError('version.dart 缺少 $name 常量');
      return int.parse(m.group(1)!);
    }

    return (
      parse('major'),
      parse('minor'),
      parse('patch'),
      parse('build'),
    );
  }

  /// 写入全新的 version.dart。
  Future<void> _writeVersion(int M, int m, int p, int b) async {
    final content = '''// Auto-generated by scripts/version_bump.dart. DO NOT EDIT manually.
class Version {
  static const int major = $M;
  static const int minor = $m;
  static const int patch = $p;
  static const int build = $b;

  /// Display version: "$M.$m.$p"
  static const String display = '$M.$m.$p';

  /// Flutter pubspec version: "$M.$m.$p+$b"
  static const String pubspec = '$M.$m.$p+$b';

  /// 3-part version for platform files: "$M.$m.$p"
  static const String platform = '$M.$m.$p';
}
''';
    await versionFile.writeAsString(content);
  }

  /// 确保 build_info.dart 引用了 Version.display。
  /// 如果硬编码了字符串版本号则自动修复。
  Future<void> _ensureBuildInfoUsesVersion() async {
    final src = await buildInfoFile.readAsString();

    // 如果已经用了 Version.display 就跳过
    if (src.contains('Version.display')) return;

    // 替换硬编码字符串 `'X.Y.Z'` → `Version.display`
    final fixed = src.replaceAllMapped(
      RegExp(r"(appVersion\s*=\s*)'[0-9.]+'"),
      (m) => '${m.group(1)}Version.display',
    );
    if (fixed != src) {
      await buildInfoFile.writeAsString(fixed);
    }
  }

  // ── 变更检测 ────────────────────────────────────────────────────────

  /// 检测 lib/ 下的变更，返回 (bumpMinor, bumpPatch)。
  (bool, bool) _detectBump() {
    final files = _getChangedFilesWithStatus();
    if (files.isEmpty) return (false, false);

    bool hasNewPage = false;
    bool hasLibChange = false;

    for (final entry in files.entries) {
      final f = entry.key;
      final status = entry.value;

      final inPages = f.startsWith('lib/presentation/pages/') && f.endsWith('.dart');
      final inLib = f.startsWith('lib/') && f.endsWith('.dart');
      final isGenerated = f.contains('.g.') || f.contains('.freezed.');

      if (inPages && !isGenerated) {
        hasLibChange = true;
        if (status == 'A' || status == '??') {
          hasNewPage = true;
        }
      } else if (inLib && !isGenerated) {
        hasLibChange = true;
      }
    }

    return (hasNewPage, hasLibChange && !hasNewPage);
  }

  /// 获取变更文件及状态。
  /// Map<filePath, status>: status = M/A/D/R/??（git status 风格）
  Map<String, String> _getChangedFilesWithStatus() {
    final gitDir = Directory(p.join(root, '.git'));
    if (!gitDir.existsSync()) {
      return {};
    }

    // 优先使用 HEAD~1..HEAD（最近一次提交的变更）
    final committed = _runGit(
      ['diff', '--name-status', 'HEAD~1', 'HEAD'],
    );
    if (committed != null && committed.trim().isNotEmpty) {
      return _parseStatusLines(committed);
    }

    // 回退：未提交的变更（staged + unstaged + untracked）
    // staged
    final staged = _runGit(['diff', '--name-status', '--cached']);
    // unstaged
    final unstaged = _runGit(['diff', '--name-status']);
    // untracked
    final untracked = _runGit(
      ['status', '--porcelain', '--untracked-files=normal'],
    );

    final result = <String, String>{};
    if (staged != null) result.addAll(_parseStatusLines(staged));
    if (unstaged != null) result.addAll(_parseStatusLines(unstaged));
    if (untracked != null) {
      for (final line in untracked.split('\n')) {
        final trimmed = line.trim();
        if (trimmed.isEmpty) continue;
        // Porcelain format: "?? path/to/file"
        if (trimmed.startsWith('??')) {
          final path = trimmed.substring(2).trim();
          if (path.isNotEmpty) result[path] = '??';
        } else {
          // XY status, e.g. "M lib/foo.dart" or "A lib/bar.dart"
          // For unstaged/staged, X is staging area, Y is working tree
          final status = trimmed[0];
          final path = trimmed.substring(1).trim();
          if (path.isNotEmpty && 'MARD'.contains(status)) {
            // Only set if not already set with a more important status
            result.putIfAbsent(path, () => status);
          }
        }
      }
    }

    return result;
  }

  /// 解析 `git diff --name-status` 输出。
  /// 每行格式: "M\tlib/foo.dart" 或 "A\tlib/new.dart"
  Map<String, String> _parseStatusLines(String output) {
    final result = <String, String>{};
    for (final line in output.split('\n')) {
      final trimmed = line.trim();
      if (trimmed.isEmpty) continue;
      // name-status 格式: status TAB path
      final tabIdx = trimmed.indexOf('\t');
      if (tabIdx < 1) continue;
      final status = trimmed.substring(0, tabIdx).trim();
      final path = trimmed.substring(tabIdx + 1).trim();
      if (path.isNotEmpty && 'MARD'.contains(status[0])) {
        result[path] = status[0];
      }
    }
    return result;
  }

  /// 运行 git 命令，返回 stdout 或 null（出错时）。
  String? _runGit(List<String> args) {
    try {
      final result = Process.runSync('git', args, workingDirectory: root);
      if (result.exitCode != 0) return null;
      return (result.stdout as String).trim();
    } catch (_) {
      return null;
    }
  }

  // ── Pubspec 构建号 ─────────────────────────────────────────────────

  /// 覆盖 pubspec.yaml 的 version 行，确保构建号正确。
  /// applyVersion 会把构建号写成 +0，我们需要改成真实的 +build。
  Future<void> _updatePubspecBuild(
    int M, int m, int P, int b,
  ) async {
    final pubspec = File(p.join(root, 'pubspec.yaml'));
    var src = await pubspec.readAsString();
    final expected = '$M.$m.$P+$b';
    src = src.replaceAllMapped(
      RegExp(r'(version:\s*)[0-9.+]+\d*'),
      (match) => '${match.group(1)}$expected',
    );
    await pubspec.writeAsString(src);
  }
}
